### ISSUE TITLE
Acknowledge testing dependencies in pyproject.toml

### ISSUE THREAD

**Issue by jesper-friis** [SINTEF/ci-cd#93]
PR https://github.com/EMMC-ASBL/tripper/pull/52 fails due to external CI/CD tests implemented in this repo.

See issue https://github.com/EMMC-ASBL/tripper/issues/48 for a motivation for the failing PR.

The only change in the PR was to move some optional dependencies from `dependencies` to `testing` in pyproject.toml. 
Since this is a testing framework, it should acknowledge testing dependencies.

**Comment by CasperWA** [comment]
It's up to the given repository that uses `ci-cd` to parse the correct extra installations: https://sintef.github.io/ci-cd/latest/workflows/ci_tests/#run-pylint-safety https://sintef.github.io/ci-cd/latest/workflows/ci_tests/#build-mkdocs-documentation

Here I've linked the documentation for the tests that seems to fail in your link.

Since this is not an issue of this repository, I am closing this issue. One should however probably be opened and fixed in your repository.
